language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t raviconsul/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true raviconsul/react-test npm test -- --coverage

after_success:
    - docker build -t 0197/multi-client ./client
    - docker build -t 0197/multi-nginx ./nginx
    - docker build -t 0197/multi-server ./server
    - docker build -t 0197/multi-worker ./worker
    # Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to docker hub
    - docker push 0197/multi-client
    - docker push 0197/multi-nginx
    - docker push 0197/multi-server
    - docker push 0197/multi-worker